
-- Complete migration: 3-level hierarchy (categories -> families -> subfamilies)

-- 1. Clean up: Drop all constraints and old tables
ALTER TABLE analytics_events DROP CONSTRAINT IF EXISTS analytics_events_subcategory_id_fkey;
ALTER TABLE analytics_events DROP CONSTRAINT IF EXISTS analytics_events_subfamily_id_fkey;
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_subcategory_id_fkey;
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_subfamily_id_fkey;
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_family_id_fkey;

DROP TABLE IF EXISTS subfamilies_new CASCADE;
DROP TABLE IF EXISTS subfamilies CASCADE;
DROP TABLE IF EXISTS subcategories CASCADE;
DROP TABLE IF EXISTS families CASCADE;

-- 2. Add columns to categories
ALTER TABLE categories ADD COLUMN IF NOT EXISTS catalog_id text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS slug text;

-- 3. Create Families table
CREATE TABLE families (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    category_id uuid REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    slug text,
    catalog_id text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

CREATE INDEX idx_families_category_id ON families(category_id);

-- 4. Create Subfamilies table
CREATE TABLE subfamilies (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    family_id uuid REFERENCES families(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    description text,
    is_consumable boolean DEFAULT false,
    catalog_id text,
    slug text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

CREATE INDEX idx_subfamilies_family_id ON subfamilies(family_id);

-- 5. Update Products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS family_id uuid;

ALTER TABLE products 
    ADD CONSTRAINT products_subfamily_id_fkey 
    FOREIGN KEY (subcategory_id) 
    REFERENCES subfamilies(id) 
    ON DELETE SET NULL;

ALTER TABLE products
    ADD CONSTRAINT products_family_id_fkey
    FOREIGN KEY (family_id)
    REFERENCES families(id)
    ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_products_family_id ON products(family_id);

-- 6. Update analytics_events FK
ALTER TABLE analytics_events 
    ADD CONSTRAINT analytics_events_subfamily_id_fkey 
    FOREIGN KEY (subcategory_id) 
    REFERENCES subfamilies(id) 
    ON DELETE SET NULL;

-- 7. RLS for Families
ALTER TABLE families ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public families viewable by everyone" 
ON families FOR SELECT USING (true);

CREATE POLICY "Admins can insert families" 
ON families FOR INSERT WITH CHECK (has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can update families" 
ON families FOR UPDATE USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can delete families" 
ON families FOR DELETE USING (has_role(auth.uid(), 'admin'));

-- 8. RLS for Subfamilies
ALTER TABLE subfamilies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public subfamilies viewable by everyone" 
ON subfamilies FOR SELECT USING (true);

CREATE POLICY "Admins can insert subfamilies" 
ON subfamilies FOR INSERT WITH CHECK (has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can update subfamilies" 
ON subfamilies FOR UPDATE USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can delete subfamilies" 
ON subfamilies FOR DELETE USING (has_role(auth.uid(), 'admin'));

-- 9. Triggers for updated_at
CREATE TRIGGER update_families_updated_at
    BEFORE UPDATE ON families
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_subfamilies_updated_at
    BEFORE UPDATE ON subfamilies
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
